name: 'Run publishing to the registry'

on:
  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2

    - name: setup node 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'

    - name: install
      shell: bash
      run: npm install
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
