name: tagpr
on:
  push:
    branches: ["main"]
jobs:
  tagpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: tagpr
        uses: Songmu/tagpr@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ./.github/actions/publish
        if: "steps.tagpr.outputs.tag != ''"
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
